import {useCallback,useEffect,useRef,useState,type FormEvent,type ReactNode} from "react";
type Farm={id:string;name:string;region:string;area:string;description:string;price:number;eveningPrice:number;capacity:number;amenities:string;images:string[];published:boolean;revision:number;confirmedBookings?:number};
type Booking={id:string;farmId:string;farmName:string;date:string;period:"morning"|"evening"|"full_day";guests:number;name:string;phone:string;notes:string;total:number;status:string};
type Draft=Omit<Farm,"id"|"revision">&{id?:string;revision?:number};
const money=(n:number)=>new Intl.NumberFormat("ar-IQ").format(n)+" د.ع";
const periodTitles={morning:"صباحي · ٧ ص — ٦ م",evening:"مسائي · ٧ م — ٤ ص اليوم التالي",full_day:"يوم كامل · حجز سابق"};
function endDay(date:string){return new Date(new Date(date+"T12:00:00Z").getTime()+86400000).toISOString().slice(0,10);}
const states:Record<string,string>={pending:"بانتظار الموافقة",confirmed:"مؤكد",rejected:"مرفوض",cancelled:"ملغي"};
const blank=():Draft=>({name:"",region:"بغداد",area:"",description:"",price:100000,eveningPrice:100000,capacity:20,amenities:"",images:["/assets/standalone-farm.svg"],published:false});
function Calendar({value,onChange,today,blocked=[],ready=true,bookings}:{value:string;onChange:(d:string)=>void;today:string;blocked?:string[];ready?:boolean;bookings?:Booking[]}){const [month,setMonth]=useState(today.slice(0,7));const [year,m]=month.split("-").map(Number),count=new Date(Date.UTC(year,m,0)).getUTCDate(),offset=new Date(Date.UTC(year,m-1,1)).getUTCDay(),limit=new Date(Date.now()+366*86400000).toISOString().slice(0,10);function move(delta:number){const next=new Date(Date.UTC(year,m-1+delta,1)).toISOString().slice(0,7);setMonth(next);if(bookings)onChange(next);}const title=new Intl.DateTimeFormat("ar-IQ",{month:"long",year:"numeric",timeZone:"UTC"}).format(new Date(Date.UTC(year,m-1,1)));return <section className="mz-calendar" aria-label={bookings?"تقويم الإدارة":"اختيار يوم الحجز"}><header className="mz-row"><button type="button" aria-label="الشهر السابق" disabled={!bookings&&month<=today.slice(0,7)} onClick={()=>move(-1)}>→</button><h3>{title}</h3><button type="button" aria-label="الشهر التالي" disabled={!bookings&&month>=limit.slice(0,7)} onClick={()=>move(1)}>←</button></header>{!bookings&&<div className="mz-legend"><span>✓ متاح</span><span>× محجوز</span><span>● اختيارك</span></div>}<div className="mz-week">{["أحد","اثنين","ثلاثاء","أربعاء","خميس","جمعة","سبت"].map(d=><span key={d}>{d}</span>)}</div><div className="mz-days">{Array.from({length:offset},(_,i)=><span key={"gap"+i}/>)}{Array.from({length:count},(_,i)=>{const d=month+"-"+String(i+1).padStart(2,"0"),taken=blocked.includes(d),past=d<today||d>limit,items=bookings?.filter(b=>b.date===d&&["pending","confirmed"].includes(b.status))||[];return <button type="button" key={d} disabled={!bookings&&(!ready||taken||past)} className={bookings?items.length?"mz-day-request":"":taken?"mz-day-taken":past?"mz-day-past":"mz-day-free"} aria-pressed={value===d} aria-label={d+"، "+(bookings?items.length+" طلب أو حجز":taken?"محجوز":past?"غير متاح":"متاح")} onClick={()=>onChange(bookings&&value===d?month:d)}><span>{i+1}</span>{taken&&<small>×</small>}{!bookings&&value===d&&<small>✓</small>}{bookings&&items.length>0&&<small>{items.length}</small>}</button>;})}</div>{bookings?<><p className="mz-muted">اضغط اليوم لعرض طلباته وحجوزاته. العدد يشمل المؤكد والمنتظر.</p>{value.length===10&&<button type="button" onClick={()=>onChange(month)}>عرض كل أيام الشهر</button>}</>:<><input type="hidden" name="date" value={value}/><p role="status" className="mz-date-notice">{!ready?"جاري التحقق من الأيام المتاحة…":value?blocked.includes(value)?"صار هذا اليوم محجوزاً. اختار يوماً آخر.":"موعد طلعتك: "+new Intl.DateTimeFormat("ar-IQ",{weekday:"long",day:"numeric",month:"long",timeZone:"UTC"}).format(new Date(value+"T12:00:00Z")):"الحجز يبدأ من اليوم فصاعداً. اختار يوماً أخضر."}</p></>}</section>;}
function deviceToken(){let token=localStorage.getItem("mazraaty-device-v2");if(!token||!/^[a-f0-9]{64}$/.test(token)){token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join("");localStorage.setItem("mazraaty-device-v2",token);}return token;}
async function api<T>(path:string,method="GET",value?:unknown,guest=false):Promise<T>{
 const headers:Record<string,string>={};if(guest)headers["X-Device-Token"]=deviceToken();
 const multipart=value instanceof FormData;if(value!==undefined&&!multipart)headers["Content-Type"]="application/json";
 const res=await fetch("/api/v2/"+path,{method,headers,credentials:"same-origin",cache:"no-store",body:value===undefined?undefined:multipart?value as FormData:JSON.stringify(value)});
 const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error?.message||"تعذر الاتصال. تحقق من الإنترنت وحاول مجدداً.");return data;
}
function Modal({title,close,children,notice}:{title:string;close:()=>void;children:ReactNode;notice?:string}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal();},[]);return <dialog ref={ref} className="mz-dialog" onCancel={e=>{e.preventDefault();close();}}><header className="mz-row"><h2>{title}</h2><button className="mz-icon" aria-label="إغلاق" onClick={close}>×</button></header>{notice&&<p className="mz-message" role="status">{notice}</p>}{children}</dialog>;}
export function Mazraaty({owner}:{owner:boolean}){
 const [farms,setFarms]=useState<Farm[]>([]),[bookings,setBookings]=useState<Booking[]>([]),[ready,setReady]=useState(false),[auth,setAuth]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[tab,setTab]=useState("farms"),[query,setQuery]=useState(""),[region,setRegion]=useState("الكل"),[selected,setSelected]=useState<Farm|null>(null),[draft,setDraft]=useState<Draft|null>(null),[privacy,setPrivacy]=useState(false),[favorites,setFavorites]=useState<string[]>([]);
 const [cancelBooking,setCancelBooking]=useState<Booking|null>(null);
 const [dates,setDates]=useState<string[]>([]),[availabilityReady,setAvailabilityReady]=useState(false),[bookingDate,setBookingDate]=useState(""),[bookingPeriod,setBookingPeriod]=useState<"morning"|"evening">("morning");
 const [filtersOpen,setFiltersOpen]=useState(false),[maxPrice,setMaxPrice]=useState(""),[minGuests,setMinGuests]=useState(""),[service,setService]=useState("الكل"),[sort,setSort]=useState("default"),[bookingStatus,setBookingStatus]=useState("all"),[calendarDate,setCalendarDate]=useState("");
 const [account,setAccount]=useState({enabled:false,authenticated:false,phone:""}),[accountOpen,setAccountOpen]=useState(false),[accountStep,setAccountStep]=useState<"phone"|"code">("phone"),[accountPhone,setAccountPhone]=useState(""),[accountCode,setAccountCode]=useState(""),[retryAt,setRetryAt]=useState(0),[clock,setClock]=useState(Date.now());
 useEffect(()=>{const id=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(id);},[]);
 const requestRef=useRef({payload:"",id:""}),refreshGeneration=useRef(0);
 const refresh=useCallback(async(quiet=false)=>{const generation=++refreshGeneration.current;if(!quiet)setLoading(true);try{
   if(owner){const status=await api<{authenticated:boolean}>("owner/status");if(generation!==refreshGeneration.current)return;setAuth(status.authenticated);const [a,b]=await Promise.all([api<{farms:Farm[]}>("owner/farms"),api<{bookings:Booking[]}>("owner/bookings")]);if(generation!==refreshGeneration.current)return;setFarms(a.farms);setBookings(b.bookings);}
   else{const [a,status]=await Promise.all([api<{farms:Farm[]}>("catalog"),api<{enabled:boolean;authenticated:boolean;phone:string}>("account/status")]);const b=(!status.enabled||status.authenticated)?await api<{bookings:Booking[]}>("bookings","GET",undefined,true):{bookings:[]};if(generation!==refreshGeneration.current)return;setAccount(status);setFarms(a.farms);setBookings(b.bookings);}
   setReady(true);
  }catch(e){if(generation!==refreshGeneration.current)return;if(!quiet)setMessage((e as Error).message);}finally{if(generation===refreshGeneration.current)setLoading(false);}},[owner]);
 useEffect(()=>{void refresh();if(!owner){try{setFavorites(JSON.parse(localStorage.getItem("mazraaty-favorites-v2")||"[]"));}catch{setFavorites([]);}}
 const id=setInterval(()=>{if(document.visibilityState==="visible")void refresh(true);},20000);return()=>{clearInterval(id);refreshGeneration.current++;};},[refresh,owner]);
 useEffect(()=>{if(!selected||owner)return;let cancelled=false;setDates([]);setBookingDate("");setAvailabilityReady(false);const check=()=>api<{dates:string[]}>("unavailable?farmId="+encodeURIComponent(selected.id)+"&period="+bookingPeriod).then(a=>{if(!cancelled){setDates(a.dates);setAvailabilityReady(true);}}).catch(e=>{if(!cancelled){setAvailabilityReady(false);setMessage(e.message);}});void check();const interval=setInterval(()=>{if(document.visibilityState==="visible")void check();},15000);return()=>{cancelled=true;clearInterval(interval);};},[selected,owner,bookingPeriod]);
 async function act(fn:()=>Promise<void>,success:string){if(busy)return;setBusy(true);setMessage("");try{await fn();setMessage(success);await refresh(true);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 function favorite(id:string){const next=favorites.includes(id)?favorites.filter(x=>x!==id):[...favorites,id];setFavorites(next);localStorage.setItem("mazraaty-favorites-v2",JSON.stringify(next));}
 const filtered=farms.filter(f=>(region==="الكل"||f.region===region)&&(f.name+" "+f.area+" "+f.description).includes(query)&&(tab!=="favorites"||favorites.includes(f.id))&&(!maxPrice||Math.min(f.price,f.eveningPrice)<=Number(maxPrice))&&(!minGuests||f.capacity>=Number(minGuests))&&(service==="الكل"||f.amenities.split(/[,،]/).map(x=>x.trim()).includes(service))).sort((a,b)=>sort==="low"?Math.min(a.price,a.eveningPrice)-Math.min(b.price,b.eveningPrice):sort==="high"?Math.min(b.price,b.eveningPrice)-Math.min(a.price,a.eveningPrice):sort==="capacity"?b.capacity-a.capacity:0);
 const popularFarms=!owner&&tab==="farms"?filtered.filter(f=>(f.confirmedBookings||0)>0).sort((a,b)=>(b.confirmedBookings||0)-(a.confirmedBookings||0)||a.id.localeCompare(b.id)).slice(0,3):[];
 const popularIds=new Set(popularFarms.map(f=>f.id));
 const remainingFarms=filtered.filter(f=>!popularIds.has(f.id));
 const renderFarm=(f:Farm)=><article className="mz-farm" key={f.id}><button className="mz-photo" onClick={()=>owner?setDraft({...f}):setSelected(f)} aria-label={"تفاصيل "+f.name}><img src={f.images[0]} alt={f.name} loading="lazy"/>{f.images[0].endsWith(".svg")&&<span className="mz-illustration">رسم توضيحي</span>}</button><div className="mz-farm-body"><div className="mz-row"><span className="mz-muted">{f.region} · {f.area}</span>{owner?<span className="mz-tag">{f.published?"منشورة":"مخفية"}</span>:<button className="mz-icon" aria-label={favorites.includes(f.id)?"إزالة من المفضلة":"إضافة للمفضلة"} aria-pressed={favorites.includes(f.id)} onClick={()=>favorite(f.id)}>{favorites.includes(f.id)?"♥":"♡"}</button>}</div><h2>{f.name}</h2><p className="mz-muted">حتى {f.capacity} شخص · {f.amenities||"راجع تفاصيل المزرعة"}</p><div className="mz-row"><strong>من {money(Math.min(f.price,f.eveningPrice))}<small className="mz-muted"> / فترة</small></strong><button className="mz-secondary" onClick={()=>owner?setDraft({...f}):setSelected(f)}>{owner?"تعديل":"التفاصيل"}</button></div></div></article>;
 const serviceOptions=Array.from(new Set(farms.flatMap(f=>f.amenities.split(/[,،]/).map(x=>x.trim()).filter(Boolean)))).sort();
 const heroFarm=farms.find(f=>f.published&&!f.images[0]?.endsWith(".svg"));
 const today=new Date(Date.now()+10800000).toISOString().slice(0,10);
 const shownBookings=bookings.filter(b=>(bookingStatus==="all"||b.status===bookingStatus)&&(tab!=="calendar"||b.date.startsWith(calendarDate||today.slice(0,7))));
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,values=new FormData(form);await act(async()=>{await api("login","POST",{password:values.get("password")});form.reset();setAuth(true);},"تم تسجيل الدخول.");}
 async function saveFarm(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!draft)return;await act(async()=>{await api(draft.id?"owner/farms/"+draft.id:"owner/farms",draft.id?"PATCH":"POST",draft);setDraft(null);},"تم حفظ المزرعة.");}
 async function upload(file:File){if(!draft)return;await act(async()=>{const bitmap=await createImageBitmap(file);const scale=Math.min(1,1400/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const ctx=canvas.getContext("2d");if(!ctx)throw new Error("تعذر تجهيز الصورة.");ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error("تعذر تجهيز الصورة.")),"image/jpeg",0.84));if(blob.size>2097152)throw new Error("الصورة كبيرة. اختار صورة أصغر.");const form=new FormData();form.append("file",blob,"farm.jpg");const result=await api<{url:string}>("owner/photos","POST",form);setDraft(current=>current?{...current,images:[...current.images.filter(x=>x!=="/assets/standalone-farm.svg"),result.url].slice(0,6)}:null);},"تم رفع الصورة. اضغط حفظ لإضافتها للمزرعة.");}
 async function book(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;if(account.enabled&&!account.authenticated){setAccountOpen(true);return;}const form=new FormData(e.currentTarget),date=String(form.get("date"));if(!date){setMessage("اختار يوم طلعتك من التقويم أولاً.");return;}if(date<today){setMessage("الحجز يبدأ من اليوم فصاعداً؛ ما تگدر تحجز تاريخ قديم.");return;}if(dates.includes(date)){setMessage("هذا اليوم محجوز. اختار يوماً آخر.");return;}
 const value={farmId:selected.id,date,period:bookingPeriod,guests:Number(form.get("guests")),name:String(form.get("name")),phone:account.authenticated?account.phone:String(form.get("phone")),notes:String(form.get("notes")||"")};const payload=JSON.stringify(value);if(requestRef.current.payload!==payload)requestRef.current={payload,id:crypto.randomUUID()};
 await act(async()=>{try{await api("bookings","POST",{...value,requestId:requestRef.current.id},true);}catch(e){const latest=await api<{dates:string[]}>("unavailable?farmId="+encodeURIComponent(selected.id)+"&period="+bookingPeriod).catch(()=>null);if(latest){setDates(latest.dates);if(latest.dates.includes(date))setBookingDate("");}throw e;}setSelected(null);setTab("bookings");requestRef.current={payload:"",id:""};},"وصل طلبك للإدارة. يبقى بانتظار الموافقة، ولم يُحصّل أي مبلغ.");}
 async function accountSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setMessage("");try{if(accountStep==="phone"){const sent=await api<{phone:string}>("account/start","POST",{phone:accountPhone});setAccountPhone(sent.phone);setAccountStep("code");setRetryAt(Date.now()+60000);setAccountCode("");setMessage("طلبنا إرسال الرمز برسالة نصية. أدخله هنا حتى تكمل الدخول.");}else{const status=await api<{authenticated:boolean;phone:string}>("account/check","POST",{code:accountCode},true);setAccount({enabled:true,...status});setAccountOpen(false);setAccountStep("phone");setAccountCode("");await refresh(true);setMessage("تم تسجيل الدخول. حجوزاتك مرتبطة برقم هاتفك.");}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <div className={"mz-app "+(owner?"mz-owner":"")}>
 <header className="mz-top"><div className="mz-brand"><img src="/assets/mazraaty-logo.svg" alt="" width="42" height="42"/><div><strong>مزرعتي</strong><small>{owner?"إدارة المزارع والحجوزات":"يوم حلو، بمكان أحلى"}</small></div></div><button className="mz-icon" disabled={busy||loading} onClick={()=>void refresh()} aria-label="تحديث البيانات">↻</button></header>
 <main className="mz-main">
 {message&&<div role="status" className="mz-message"><p>{message}</p><button className="mz-icon" aria-label="إخفاء الرسالة" onClick={()=>setMessage("")}>×</button></div>}
 {owner&&!auth?<section className="mz-login"><span className="mz-eyebrow">للإدارة فقط</span><h1>كل مزارعك، من مكان واحد.</h1><p>سجل دخولك لإضافة المزارع، تعديلها، ومتابعة طلبات الزبائن.</p><form onSubmit={login}><label>كلمة مرور الإدارة<input name="password" type="password" autoComplete="current-password" required maxLength={256}/></label><button className="mz-primary" disabled={busy}>{busy?"جاري الدخول…":"دخول الإدارة"}</button></form><p className="mz-muted">إذا لم يُفعّل الدخول بعد، جهّز كلمة الإدارة من إعدادات المشروع.</p></section>:<>
 {owner?<section className="mz-hero mz-row"><div><span className="mz-eyebrow">لوحة الإدارة</span><h1>خلّ نرتّب اليوم.</h1><p>{bookings.filter(b=>b.status==="pending").length} طلب بانتظارك · {farms.filter(f=>f.published).length} مزرعة منشورة</p></div><button className="mz-primary" disabled={busy} onClick={()=>setDraft(blank())}>+ إضافة مزرعة</button></section>:<section className="mz-discover"><div className="mz-discover-copy"><span className="mz-eyebrow">مزارع سياحية في العراق</span><h1>يوم بعيد<br/>عن الزحمة.</h1><p>اختار مكان يجمعكم. صور المزرعة وخدماتها وسعرها، قبل ما تحجز.</p><button className="mz-primary" onClick={()=>document.getElementById("mz-results")?.scrollIntoView({behavior:"smooth"})}>استكشف المزارع ←</button></div><div className="mz-discover-image"><img src={heroFarm?.images[0]||"/assets/standalone-farm.svg"} alt={heroFarm?heroFarm.name:"رسم توضيحي لمزرعة سياحية"}/><span className="mz-image-note">{heroFarm?heroFarm.region+" · "+heroFarm.name:"مزارع سياحية · العراق · رسم توضيحي"}</span></div></section>}
 {!owner&&account.enabled&&<section className="mz-account-strip"><div><strong>{account.authenticated?"حسابك مرتبط برقمك":"حجوزاتك وياك، بأي جهاز"}</strong><small>{account.authenticated?account.phone:"سجل برقم هاتفك عند الحجز"}</small></div>{account.authenticated?<button disabled={busy} onClick={()=>void act(async()=>{await api("account/logout","POST",{});setAccount({enabled:true,authenticated:false,phone:""});setBookings([]);},"تم تسجيل الخروج.")}>خروج</button>:<button onClick={()=>{setAccountOpen(true);setAccountStep("phone");}}>دخول / إنشاء حساب</button>}</section>}
 {owner&&auth&&<section className="mz-stats" aria-label="ملخص الإدارة"><div><small>بانتظار الموافقة</small><strong>{bookings.filter(b=>b.status==="pending").length}</strong></div><div><small>حجوزات مؤكدة</small><strong>{bookings.filter(b=>b.status==="confirmed").length}</strong></div><div><small>مزارع منشورة</small><strong>{farms.filter(f=>f.published).length}</strong></div></section>}
 <nav className={"mz-tabs "+(!owner?"mz-bottom-nav":"")} aria-label="أقسام التطبيق">{[["farms",owner?"المزارع":"استكشف","⌂"],...(!owner?[["favorites","المفضلة","♡"]]:[["calendar","التقويم","▦"]]),["bookings",owner?"طلبات الزبائن":"حجوزاتي","▤"]].map(([key,label,icon])=><button key={key} aria-current={tab===key?"page":undefined} onClick={()=>{setTab(key);setCalendarDate("");}}><span className="mz-nav-icon" aria-hidden="true">{icon}</span><span>{label}</span></button>)}{owner&&<button disabled={busy} onClick={()=>void act(async()=>{await api("owner/logout","POST",{});setAuth(false);setFarms([]);setBookings([]);},"تم تسجيل الخروج.")}>خروج</button>}</nav>
 {tab!=="bookings"&&tab!=="calendar"?<>
 {!owner&&tab==="farms"&&<section className="mz-popular" aria-label="المزارع الأكثر حجزاً"><div className="mz-results-heading"><div><span className="mz-eyebrow">اختيارات الزبائن</span><h2>المزارع الأكثر حجزاً <span aria-hidden="true">★</span></h2><p className="mz-muted">حسب عدد الحجوزات المؤكدة، ويتحدّث تلقائياً.</p></div></div>{popularFarms.length?<div className="mz-grid">{popularFarms.map(f=>renderFarm(f))}</div>:<p className="mz-muted">أول ما تتأكد الحجوزات، تظهر هنا المزارع الأكثر حجزاً.</p>}</section>}
 <section id="mz-results" className="mz-results-heading"><div><span className="mz-eyebrow">{tab==="favorites"?"أماكن عجبتك":"اختار على ذوقك"}</span><h2>{tab==="favorites"?"مفضّلتك":popularFarms.length?"بقية المزارع":"اكتشف المزارع"}</h2></div><span className="mz-muted">{remainingFarms.length} مزرعة</span></section>
 <div className="mz-search"><label><span className="mz-sr">ابحث عن مزرعة أو منطقة</span><input type="search" placeholder="وين تحب تطلع؟ ابحث عن مكان…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label><span className="mz-sr">المحافظة</span><select value={region} onChange={e=>setRegion(e.target.value)}><option>الكل</option>{Array.from(new Set(farms.map(f=>f.region))).map(r=><option key={r}>{r}</option>)}</select></label><button className="mz-filter-toggle" aria-label="الفلاتر" aria-expanded={filtersOpen} aria-controls="mz-filters" onClick={()=>setFiltersOpen(!filtersOpen)}>☷</button></div>
 {filtersOpen&&<section id="mz-filters" className="mz-filters"><label>أعلى سعر / دينار<input type="number" min="1" placeholder="بدون حد" value={maxPrice} onChange={e=>setMaxPrice(e.target.value)}/></label><label>عدد أفراد الطلعة<input type="number" min="1" max="1000" placeholder="أي سعة" value={minGuests} onChange={e=>setMinGuests(e.target.value)}/></label><label>الخدمات<select value={service} onChange={e=>setService(e.target.value)}><option>الكل</option>{serviceOptions.map(x=><option key={x}>{x}</option>)}</select></label><label>الترتيب<select value={sort} onChange={e=>setSort(e.target.value)}><option value="default">الترتيب الحالي</option><option value="low">السعر: الأقل أولاً</option><option value="high">السعر: الأعلى أولاً</option><option value="capacity">السعة: الأكبر أولاً</option></select></label><button onClick={()=>{setMaxPrice("");setMinGuests("");setService("الكل");setSort("default");setRegion("الكل");setQuery("");}}>مسح الفلاتر</button></section>}
 {loading&&!ready?<div className="mz-grid" aria-label="جاري تحميل المزارع">{[1,2,3].map(i=><div className="mz-skeleton" key={i}/>)}</div>:remainingFarms.length?<div className="mz-grid">{remainingFarms.map(f=>renderFarm(f))}</div>:popularFarms.length?null:<section className="mz-empty"><h2>{loading?"جاري الاتصال…":tab==="favorites"?"بعد ما اخترت مفضلة":"ماكو مزارع بهالبحث"}</h2><p>{owner?"أضف مزرعة وانشرها حتى تظهر للزبائن.":"حدّث القائمة أو جرّب محافظة ثانية."}</p><button onClick={()=>{setQuery("");setRegion("الكل");void refresh();}}>تحديث القائمة</button></section>}</>:<section className="mz-bookings">{tab==="calendar"&&<Calendar bookings={bookings} value={calendarDate} onChange={setCalendarDate} today={today}/>}<div className="mz-booking-heading"><h2>{tab==="calendar"?"طلبات الأيام المحددة":owner?"طلبات الزبائن":"طلعاتك وحجوزاتك"}</h2><p className="mz-muted">{owner?"تابع الطلبات ووافق على المواعيد المناسبة.":"كل طلب وحالته، بمكان واحد."}</p>{!owner&&account.enabled&&!account.authenticated&&<button className="mz-primary" onClick={()=>setAccountOpen(true)}>سجل الدخول لعرض حجوزاتك</button>}</div><div className="mz-status-filters" aria-label="حالة الحجز">{[["all","الكل"],...Object.entries(states)].map(([key,label])=><button key={key} aria-pressed={bookingStatus===key} onClick={()=>setBookingStatus(key)}>{label}<small>{bookings.filter(b=>key==="all"||b.status===key).length}</small></button>)}</div>{!shownBookings.length?<div className="mz-empty"><h2>ماكو طلبات بهالاختيار</h2><p>{owner?"طلبات الزبائن تظهر هنا حتى توافق عليها.":"اختار مزرعة وأرسل طلب الحجز."}</p></div>:shownBookings.map(b=><article key={b.id} className="mz-booking"><div className="mz-row"><h2>{b.farmName}</h2><span className={"mz-tag mz-"+b.status}>{states[b.status]||b.status}</span></div><p className="mz-period-summary">{periodTitles[b.period]||periodTitles.full_day}{b.period==="evening"&&<small> · تنتهي {endDay(b.date)}</small>}</p><div className="mz-booking-facts"><div><small>تاريخ بداية الطلعة</small><strong>{b.date}</strong></div><div><small>عدد الزوار</small><strong>{b.guests} شخص</strong></div><div><small>سعر الحجز</small><strong>{money(b.total)}</strong></div></div>{owner&&<p>{b.name||"حُذفت بيانات الزبون"} {b.phone&&<a href={"tel:"+b.phone}>{b.phone}</a>}</p>}{b.notes&&<p>{b.notes}</p>}<p className="mz-muted">الدفع الإلكتروني غير مفعّل. تأكيد الحجز لا يعني استلام دفعة.</p><div className="mz-row">{owner&&b.status==="pending"&&<><button className="mz-primary" disabled={busy} onClick={()=>void act(async()=>{await api("owner/bookings/"+b.id,"PATCH",{status:"confirmed"});},"تم تأكيد الحجز.")}>تأكيد الحجز</button><button disabled={busy} onClick={()=>void act(async()=>{await api("owner/bookings/"+b.id,"PATCH",{status:"rejected"});},"تم رفض الطلب.")}>رفض</button></>}{["pending","confirmed"].includes(b.status)&&<button disabled={busy} onClick={()=>{setMessage("");setCancelBooking(b);}}>إلغاء الحجز</button>}</div></article>)}</section>}
 </>}
 <footer className="mz-footer"><button onClick={()=>setPrivacy(true)}>الخصوصية والتواصل</button><a href="tel:+9647708248458">اتصل بنا</a><span>مزرعتي · العراق</span></footer>
 </main>
 {cancelBooking&&<Modal notice={message} title="إلغاء الحجز" close={()=>!busy&&setCancelBooking(null)}><h3>{cancelBooking.farmName}</h3><p>{cancelBooking.date} · {periodTitles[cancelBooking.period]||periodTitles.full_day}</p><p>تريد تلغي هذا الحجز؟ بعد الإلغاء يصير الموعد متاح للحجز من جديد.</p><div className="mz-row"><button disabled={busy} onClick={()=>setCancelBooking(null)}>الاحتفاظ بالحجز</button><button className="mz-primary" disabled={busy} onClick={()=>void act(async()=>{const id=cancelBooking.id;const result=await api<{booking:Booking}>(owner?"owner/bookings/"+id:"bookings/"+id+"/cancel",owner?"PATCH":"POST",owner?{status:"cancelled"}:{},!owner);if(result.booking?.status!=="cancelled")throw new Error("حالة الحجز تغيّرت. حدّث القائمة وحاول مجدداً.");setCancelBooking(null);},"تم إلغاء الحجز.")}>{busy?"جاري الإلغاء…":"نعم، إلغاء الحجز"}</button></div></Modal>}
 {selected&&<Modal notice={message} title={selected.name} close={()=>!busy&&setSelected(null)}><div className="mz-gallery">{selected.images.map(src=><img key={src} src={src} alt={selected.name}/>)}</div><div className="mz-detail-facts"><div><small>المكان</small><strong>{selected.region} · {selected.area}</strong></div><div><small>السعة</small><strong>حتى {selected.capacity} شخص</strong></div><div><small>سعر الفترة</small><strong>صباحي {money(selected.price)}</strong><strong>مسائي {money(selected.eveningPrice)}</strong></div></div><h3>عن المكان</h3><p className="mz-description">{selected.description}</p><div className="mz-amenities">{selected.amenities.split(/[,،]/).filter(Boolean).map(x=><span key={x}>{x.trim()}</span>)}</div><form onSubmit={book} className="mz-form"><h3>اختار الفترة وموعد طلعتك</h3><div className="mz-period-picker" role="group" aria-label="فترة الحجز">{(["morning","evening"] as const).map(p=><button type="button" key={p} disabled={busy} aria-pressed={bookingPeriod===p} onClick={()=>setBookingPeriod(p)}><span aria-hidden="true">{p==="morning"?"☀":"☾"}</span><strong>{p==="morning"?"صباحي":"مسائي"}</strong><small>{p==="morning"?"٧ الصبح — ٦ المغرب":"٧ المغرب — ٤ صبح اليوم التالي"}</small><b>{money(p==="morning"?selected.price:selected.eveningPrice)}</b></button>)}</div><p className="mz-muted">التقويم يبين المتاح للفترة المختارة. الصباحي والمسائي ينحجزن بشكل مستقل.</p><Calendar blocked={dates} value={bookingDate} onChange={setBookingDate} ready={availabilityReady&&!busy} today={today}/><label>عدد أفراد الطلعة<input name="guests" type="number" min="1" max={selected.capacity} defaultValue={Math.min(5,selected.capacity)} required/></label><label>اسمك<input name="name" autoComplete="name" maxLength={100} required/></label>{account.enabled?<div className="mz-account-note">{account.authenticated?<p>رقمك الموثق: <b dir="ltr">{account.phone}</b></p>:<><p>وثّق رقمك برسالة نصية حتى تحفظ حجزك وترجعله بأي جهاز.</p><button type="button" className="mz-secondary" onClick={()=>{setAccountOpen(true);setAccountStep("phone");}}>تسجيل الدخول برقم الهاتف</button></>}</div>:<label>رقم الهاتف<input name="phone" type="tel" autoComplete="tel" inputMode="tel" placeholder="07…" maxLength={30} required/></label>}<label>ملاحظات اختيارية<textarea name="notes" maxLength={1000}/></label><p className="mz-muted">الطلب يحتاج موافقة الإدارة. لا توجد دفعة إلكترونية حالياً.</p><div className="mz-bookbar"><strong>{money(bookingPeriod==="morning"?selected.price:selected.eveningPrice)}<small> / {bookingPeriod==="morning"?"صباحي":"مسائي"}</small></strong><button className="mz-primary" disabled={busy||!availabilityReady||!bookingDate||dates.includes(bookingDate)}>{busy?"جاري الإرسال…":account.enabled&&!account.authenticated?"سجل الدخول للحجز":"إرسال طلب الحجز"}</button></div></form></Modal>}
 {draft&&auth&&<Modal notice={message} title={draft.id?"تعديل المزرعة":"إضافة مزرعة"} close={()=>!busy&&setDraft(null)}><form onSubmit={saveFarm} className="mz-form"><label>اسم المزرعة<input value={draft.name} maxLength={100} required onChange={e=>setDraft({...draft,name:e.target.value})}/></label><div className="mz-pair"><label>المحافظة<input value={draft.region} maxLength={60} required onChange={e=>setDraft({...draft,region:e.target.value})}/></label><label>المنطقة<input value={draft.area} maxLength={100} required onChange={e=>setDraft({...draft,area:e.target.value})}/></label></div><label>وصف المزرعة<textarea value={draft.description} required maxLength={2000} onChange={e=>setDraft({...draft,description:e.target.value})}/></label><div className="mz-pair"><label>سعر الصباحي / دينار<input type="number" min="1" max="100000000" required value={draft.price} onChange={e=>setDraft({...draft,price:Number(e.target.value)})}/></label><label>سعر المسائي / دينار<input type="number" min="1" max="100000000" required value={draft.eveningPrice} onChange={e=>setDraft({...draft,eveningPrice:Number(e.target.value)})}/></label><label>السعة / شخص<input type="number" min="1" max="1000" required value={draft.capacity} onChange={e=>setDraft({...draft,capacity:Number(e.target.value)})}/></label></div><label>الخدمات، افصل بينها بفاصلة<textarea maxLength={500} value={draft.amenities} onChange={e=>setDraft({...draft,amenities:e.target.value})}/></label><div className="mz-thumbs">{draft.images.map(src=><div key={src}><img src={src} alt="صورة المزرعة"/>{draft.images.length>1&&<button type="button" aria-label="إزالة الصورة" disabled={busy} onClick={()=>setDraft({...draft,images:draft.images.filter(x=>x!==src)})}>×</button>}</div>)}</div><label>إضافة صورة من تلفونك<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||draft.images.length>=6} onChange={e=>{const file=e.target.files?.[0];e.target.value="";if(file)void upload(file);}}/></label>{draft.images[0]?.endsWith(".svg")&&<p className="mz-muted">الصورة الحالية رسم توضيحي؛ ارفع صور المزرعة الحقيقية.</p>}<label className="mz-check"><input type="checkbox" checked={draft.published} onChange={e=>setDraft({...draft,published:e.target.checked})}/>نشر المزرعة للزبائن</label><div className="mz-row"><button className="mz-primary" disabled={busy}>{busy?"جاري الحفظ…":"حفظ المزرعة"}</button>{draft.id&&<button type="button" disabled={busy} onClick={()=>{if(confirm("تريد تخفي المزرعة عن الزبائن؟ تبقى حجوزاتها محفوظة."))void act(async()=>{await api("owner/farms/"+draft.id,"DELETE");setDraft(null);},"تم إخفاء المزرعة.");}}>إخفاء المزرعة</button>}</div></form></Modal>}
 {accountOpen&&!owner&&<Modal notice={message} title="حسابك بمزرعتي" close={()=>{if(!busy)setAccountOpen(false);}}><div className="mz-account-heading"><span className="mz-account-symbol" aria-hidden="true">☎</span><h3>{accountStep==="phone"?"رقم واحد، كل طلعاتك":"وصلتك رسالة؟"}</h3><p>{accountStep==="phone"?"نتحقق من رقمك برسالة نصية. حسابك وحجوزاتك يبقون وياك إذا غيّرت جهازك.":"أدخل رمز التحقق المرسل إلى رقمك."}</p></div><form className="mz-form" onSubmit={accountSubmit}>{accountStep==="phone"?<><label>رقم هاتفك العراقي<input type="tel" dir="ltr" inputMode="tel" autoComplete="tel" placeholder="077…" maxLength={30} required value={accountPhone} onChange={e=>setAccountPhone(e.target.value)}/></label><p className="mz-muted">بالضغط على إرسال الرمز توافق نستعمل رقمك لإرسال رسالة تحقق وتسجيل حسابك.</p><button className="mz-primary" disabled={busy||clock<retryAt}>{busy?"جاري الإرسال…":clock<retryAt?"انتظر "+Math.ceil((retryAt-clock)/1000)+" ثانية":"إرسال رمز التحقق"}</button></>:<><p dir="ltr" className="mz-verified-phone">{accountPhone}</p><label>رمز التحقق<input className="mz-otp-input" dir="ltr" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9٠-٩]{4,10}" minLength={4} maxLength={10} required value={accountCode} onChange={e=>setAccountCode(e.target.value)}/></label><button className="mz-primary" disabled={busy}>{busy?"جاري التحقق…":"تأكيد والدخول"}</button><button type="button" disabled={busy} onClick={()=>{setAccountStep("phone");setAccountCode("");}}>تغيير الرقم أو إعادة إرسال الرمز</button></>}</form></Modal>}
 {privacy&&<Modal notice={message} title="الخصوصية والتواصل" close={()=>setPrivacy(false)}><p>نستخدم اسمك ورقم هاتفك وموعدك حتى الإدارة تتابع طلب الحجز وتتواصل وياك. بيانات المزارع والحجوزات محفوظة بخادم مستقل عن Wix.</p><p>عند تفعيل تسجيل الهاتف، نستخدم تويليو لإرسال رمز تحقق ونحفظ جلسة دخول آمنة. حجوزاتك الجديدة مرتبطة برقمك وتظهر بعد دخولك بأي جهاز. المفضلة تبقى على جهازك. الطلبات القديمة تُربط فقط بعد توثيق رقمها من نفس جهاز الحجز القديم؛ لا نربط الطلبات القديمة حسب الرقم وحده.</p><p>الإدارة تقدر تشوف طلبات الحجز. حذف بياناتك يزيل اسمك وهاتفك وملاحظاتك؛ الموعد المؤكد يبقى محجوزاً بسجل بدون بياناتك.</p><p>الدفع بكي غير مفعّل حالياً، ولا نجمع بيانات بطاقتك.</p><p>الدعم: <a href="tel:+9647708248458">07708248458</a> · <a href="mailto:laithlaith500@gmail.com">البريد الإلكتروني</a></p>{!owner&&<button disabled={busy} onClick={()=>{if(confirm("تريد تحذف بيانات طلباتك؟ ما تقدر ترجعها، والحجز المؤكد يبقى محفوظاً بدون اسمك وهاتفك."))void act(async()=>{await api("device","DELETE",undefined,true);localStorage.removeItem("mazraaty-device-v2");setBookings([]);setAccount({enabled:account.enabled,authenticated:false,phone:""});setPrivacy(false);},"تم حذف بياناتك.");}}>حذف بيانات طلباتي</button>}</Modal>}
 </div>;
}

