CREATE TABLE IF NOT EXISTS farms (id TEXT PRIMARY KEY,name TEXT NOT NULL,region TEXT NOT NULL,area TEXT NOT NULL,description TEXT NOT NULL,price INTEGER NOT NULL,capacity INTEGER NOT NULL,amenities TEXT NOT NULL,images TEXT NOT NULL,published INTEGER NOT NULL DEFAULT 0,revision INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (id TEXT PRIMARY KEY,credential_tag TEXT NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS rate_limits (id TEXT PRIMARY KEY,count INTEGER NOT NULL,expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS devices (hash TEXT PRIMARY KEY,revoked INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS bookings (id TEXT PRIMARY KEY,device_hash TEXT NOT NULL,request_id TEXT NOT NULL,payload_hash TEXT NOT NULL,farm_id TEXT NOT NULL,farm_name TEXT NOT NULL,date TEXT NOT NULL,guests INTEGER NOT NULL,customer_name TEXT NOT NULL,phone TEXT NOT NULL,notes TEXT NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',created_at TEXT NOT NULL,UNIQUE(device_hash,request_id));
CREATE TABLE IF NOT EXISTS reserved_dates (farm_id TEXT NOT NULL,date TEXT NOT NULL,booking_id TEXT NOT NULL UNIQUE,PRIMARY KEY(farm_id,date));
CREATE INDEX IF NOT EXISTS bookings_device ON bookings(device_hash);
CREATE INDEX IF NOT EXISTS bookings_created ON bookings(created_at);

