import {withCustomerAuth,phoneAuthReady} from "./customer-auth.server";
import {pushEndpoint,pushReady} from "./push.server";
import type {D1Database,R2Bucket} from "@cloudflare/workers-types";
export type SharedEnv={DB?:D1Database;STORAGE?:R2Bucket;ADMIN_PASSWORD?:string;TWILIO_ACCOUNT_SID?:string;TWILIO_AUTH_TOKEN?:string;TWILIO_VERIFY_SERVICE_SID?:string;REQUIRE_PHONE_AUTH?:string;APP_ENV?:string;DEMO_AUTH_HOST?:string;DEMO_AUTH_PHONE?:string;DEMO_AUTH_CODE?:string;PUSH_ENABLED?:string;FCM_PROJECT_ID?:string;FCM_CLIENT_EMAIL?:string;FCM_PRIVATE_KEY?:string};
class Problem extends Error{constructor(public status:number,public code:string,message:string){super(message);}}
const fail=(status:number,code:string,message:string):never=>{throw new Problem(status,code,message);};
const digest=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,"0")).join("");
function response(value:unknown,status=200,headers:Record<string,string>={}){return Response.json(value,{status,headers:{"Cache-Control":"no-store",...headers}});}
function text(value:unknown,max:number,required=true){if(typeof value!=="string"||value.trim().length>max||(required&&!value.trim()))return fail(400,"invalid_input","راجع البيانات المطلوبة.");return value.trim();}
function number(value:unknown,min:number,max:number){if(!Number.isSafeInteger(value)||Number(value)<min||Number(value)>max)return fail(400,"invalid_input","راجع السعر والسعة وعدد الأشخاص.");return Number(value);}
function identifier(value:string){if(!/^[a-zA-Z0-9-]{1,80}$/.test(value))return fail(400,"invalid_id","معرّف غير صالح.");return value;}
function day(value:unknown){const s=text(value,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(new Date(s+"T12:00:00Z").getTime())||new Date(s+"T12:00:00Z").toISOString().slice(0,10)!==s)return fail(400,"invalid_date","التاريخ غير صالح.");return s;}
function period(value:unknown){if(value!=="morning"&&value!=="evening")return fail(400,"invalid_period","اختار الفترة الصباحية أو المسائية.");return value;}
function today(){return new Date(Date.now()+10800000).toISOString().slice(0,10);}
function phone(value:unknown){const s=text(value,30).replace(/[٠-٩]/g,c=>String("٠١٢٣٤٥٦٧٨٩".indexOf(c))).replace(/[\s()-]/g,"");if(!/^(?:07\d{9}|(?:\+?964|00964)7\d{9})$/.test(s))return fail(400,"invalid_phone","أدخل رقم هاتف عراقي صحيح.");return s.startsWith("07")?"+964"+s.slice(1):"+964"+s.replace(/^(?:\+?964|00964)/,"");}
async function body(request:Request,max=16000){if(Number(request.headers.get("Content-Length")||0)>max)return fail(413,"too_large","حجم البيانات كبير.");const raw=await request.text();if(new TextEncoder().encode(raw).length>max)return fail(413,"too_large","حجم البيانات كبير.");try{const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=="object"||Array.isArray(parsed))throw new Error();return parsed as Record<string,unknown>;}catch{return fail(400,"invalid_json","تعذر قراءة البيانات.");}}
function dbOf(env:SharedEnv){if(!env.DB)return fail(503,"storage_not_ready","الخدمة قيد التجهيز.");return env.DB;}
async function rate(db:D1Database,key:string,limit:number,seconds:number){const now=Math.floor(Date.now()/1000),id=await digest(key+":"+Math.floor(now/seconds));const result=await db.prepare("INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count").bind(id,now+seconds).first<{count:number}>();if(!result||result.count>limit)return fail(429,"rate_limited","طلبات كثيرة. انتظر قليلاً وحاول مرة ثانية.");}
function csrf(request:Request){const origin=request.headers.get("Origin");if(origin!==new URL(request.url).origin)return fail(403,"origin_denied","افتح الطلب من التطبيق الرسمي.");}
function credential(env:SharedEnv){if(!env.ADMIN_PASSWORD||env.ADMIN_PASSWORD.length<16)return fail(503,"admin_not_ready","دخول الإدارة يحتاج ضبط كلمة الإدارة في إعدادات المشروع أولاً.");return env.ADMIN_PASSWORD;}
async function admin(request:Request,env:SharedEnv){const password=credential(env),cookie=request.headers.get("Cookie")||"",match=cookie.match(/(?:^|;\s*)mazraaty_admin=([a-f0-9]{64})(?:;|$)/);if(!match)return fail(401,"sign_in_required","سجل دخول الإدارة أولاً.");const row=await dbOf(env).prepare("SELECT credential_tag,expires FROM sessions WHERE id=?").bind(await digest(match[1])).first<{credential_tag:string;expires:number}>();if(!row||row.expires<Math.floor(Date.now()/1000)||row.credential_tag!==await digest(password))return fail(401,"sign_in_required","انتهت جلسة الإدارة. سجل الدخول مجدداً.");return await digest(match[1]);}
async function device(request:Request,db:D1Database,allowRevoked=false){const token=request.headers.get("X-Device-Token")||"";if(!/^[a-f0-9]{64}$/.test(token))return fail(401,"device_required","تعذر التعرف على هذا الجهاز.");const hash=await digest(token);await db.prepare("INSERT OR IGNORE INTO devices(hash,revoked) VALUES(?,0)").bind(hash).run();const row=await db.prepare("SELECT revoked FROM devices WHERE hash=?").bind(hash).first<{revoked:number}>();if(!row||(!allowRevoked&&row.revoked))return fail(401,"device_revoked","تم حذف بيانات هذا الجهاز. حدّث التطبيق للبدء من جديد.");return hash;}
type FarmRow={id:string;name:string;region:string;area:string;description:string;price:number;evening_price:number|null;capacity:number;amenities:string;images:string;published:number;revision:number};
type BookingRow={id:string;device_hash:string;request_id:string;payload_hash:string;farm_id:string;farm_name:string;date:string;period:"morning"|"evening"|"full_day";guests:number;customer_name:string;phone:string;notes:string;total:number;status:string;created_at:string};
function farmJSON(row:FarmRow){return {...row,eveningPrice:row.evening_price??row.price,images:JSON.parse(row.images),published:!!row.published};}
function bookingJSON(row:BookingRow & {review_stars?:number}){return {reviewStars:row.review_stars||0,id:row.id,farmId:row.farm_id,farmName:row.farm_name,date:row.date,period:row.period,guests:row.guests,name:row.customer_name,phone:row.phone,notes:row.notes,total:row.total,status:row.status,createdAt:row.created_at};}
function imagePath(value:unknown){const s=text(value,180);if(s!=="/assets/standalone-farm.svg"&&!/^\/api\/v2\/photos\/[a-f0-9-]{36}\.(?:jpg|png|webp)$/.test(s))return fail(400,"invalid_image","استخدم صورة مرفوعة من التطبيق.");return s;}
function farmInput(value:Record<string,unknown>){if(typeof value.published!=="boolean")return fail(400,"invalid_input","راجع حالة نشر المزرعة.");if(!Array.isArray(value.images)||value.images.length<1||value.images.length>6)return fail(400,"invalid_images","أضف من صورة واحدة إلى ست صور.");return {name:text(value.name,100),region:text(value.region,60),area:text(value.area,100),description:text(value.description,2000),price:number(value.price,1,100000000),eveningPrice:number(value.eveningPrice??value.price,1,100000000),capacity:number(value.capacity,1,1000),amenities:text(value.amenities,500,false),images:JSON.stringify(value.images.map(imagePath)),published:value.published?1:0};}
function sameSecret(a:string,b:string){if(a.length!==b.length)return false;let diff=0;for(let i=0;i<a.length;i++)diff|=a.charCodeAt(i)^b.charCodeAt(i);return diff===0;}
export async function handleShared(request:Request,env:SharedEnv):Promise<Response>{return withCustomerAuth(request,env,handleCore);}
async function handleCore(request:Request,env:SharedEnv):Promise<Response>{
 try{
  const url=new URL(request.url),path=url.pathname.replace(/^\/api\/v2\/?/,""),method=request.method,db=dbOf(env);
  if(method!=="GET"&&method!=="HEAD")csrf(request);
  if(path==="health"&&method==="GET"){await db.prepare('SELECT 1 AS ok').first();return response({online:true,adminConfigured:!!env.ADMIN_PASSWORD&&env.ADMIN_PASSWORD.length>=16,phoneConfigured:phoneAuthReady(env),pushConfigured:pushReady(env),environment:env.APP_ENV||'local'});}
  if(path==="catalog"&&method==="GET"){const rows=await db.prepare("SELECT farms.*, (SELECT COUNT(*) FROM bookings WHERE bookings.farm_id=farms.id AND bookings.status='confirmed') AS confirmed_count, (SELECT AVG(stars) FROM farm_reviews WHERE farm_id=farms.id) AS rating, (SELECT COUNT(*) FROM farm_reviews WHERE farm_id=farms.id) AS ratingCount FROM farms WHERE published=1 ORDER BY updated_at DESC").all<FarmRow & {confirmed_count:number}>();return response({farms:rows.results.map(row=>({...farmJSON(row),confirmedBookings:row.confirmed_count}))});}
  if(path==="login"&&method==="POST"){await rate(db,"login:"+request.headers.get("CF-Connecting-IP"),8,600);const value=await body(request),password=credential(env),incoming=text(value.password,256);if(!sameSecret(await digest(incoming),await digest(password)))return fail(401,"wrong_password","كلمة الإدارة غير صحيحة.");const token=Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,"0")).join("");await db.prepare("INSERT INTO sessions(id,credential_tag,expires) VALUES(?,?,?)").bind(await digest(token),await digest(password),Math.floor(Date.now()/1000)+28800).run();return response({authenticated:true},200,{"Set-Cookie":"mazraaty_admin="+token+"; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=28800"});}
  if(path.startsWith("owner/")){const session=await admin(request,env);const local=path.slice(6);
   if(local==='push/campaigns'&&method==='POST'){
    if(!pushReady(env))return fail(503,'push_not_ready','إشعارات الهاتف قيد الربط.');
    const value=await body(request),title=text(value.title,80),message=text(value.body,300),id=identifier(text(value.requestId,80));
    const previous=await db.prepare('SELECT title,body FROM push_events WHERE id=?').bind('offer:'+id).first<{title:string;body:string}>();
    if(previous){if(previous.title!==title||previous.body!==message)return fail(409,'request_conflict','تغير نص العرض. أرسل طلباً جديداً.');return response({queued:true,id});}
    await rate(db,'push-campaigns',5,86400);
    await db.batch([
     db.prepare("INSERT OR IGNORE INTO push_events(id,booking_id,role,kind,created_at,title,body) VALUES(?,'','customer','offer',?,?,?)").bind('offer:'+id,Math.floor(Date.now()/1000),title,message),
     db.prepare("INSERT OR IGNORE INTO push_deliveries(event_id,token_hash) SELECT ?,p.token_hash FROM push_devices p JOIN customer_sessions s ON s.id=p.session_id WHERE p.role='customer' AND p.marketing=1 AND s.expires>?").bind('offer:'+id,Math.floor(Date.now()/1000))
    ]);
    return response({queued:true,id},202);
   }
   if(local.startsWith("push/"))return pushEndpoint(request,env,{role:'owner',principal:await digest(credential(env)),session});
   if(local==="logout"&&method==="POST"){await db.prepare("DELETE FROM sessions WHERE id=?").bind(session).run();return response({signedOut:true},200,{"Set-Cookie":"mazraaty_admin=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"});}
   if(local==="status"&&method==="GET")return response({authenticated:true});
   if(local==="farms"&&method==="GET"){const rows=await db.prepare("SELECT * FROM farms ORDER BY updated_at DESC").all<FarmRow>();return response({farms:rows.results.map(farmJSON)});}
   if((local==="farms"&&method==="POST")||(/^farms\/[a-zA-Z0-9-]+$/.test(local)&&method==="PATCH")){
    const value=await body(request),input=farmInput(value),id=method==="POST"?crypto.randomUUID():identifier(local.slice(6));
    if(method==="POST")await db.prepare("INSERT INTO farms(id,name,region,area,description,price,evening_price,capacity,amenities,images,published,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,input.name,input.region,input.area,input.description,input.price,input.eveningPrice,input.capacity,input.amenities,input.images,input.published,new Date().toISOString()).run();
    else{const revision=number(value.revision,1,2147483647);const result=await db.prepare("UPDATE farms SET name=?,region=?,area=?,description=?,price=?,evening_price=?,capacity=?,amenities=?,images=?,published=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?").bind(input.name,input.region,input.area,input.description,input.price,input.eveningPrice,input.capacity,input.amenities,input.images,input.published,new Date().toISOString(),id,revision).run();if(!result.meta.changes)return fail(409,"farm_changed","المزرعة تغيرت من جهاز آخر. حدّث بياناتها قبل الحفظ.");}
    const saved=await db.prepare("SELECT * FROM farms WHERE id=?").bind(id).first<FarmRow>();return response({farm:farmJSON(saved!)},method==="POST"?201:200);
   }
   if(/^farms\/[a-zA-Z0-9-]+$/.test(local)&&method==="DELETE"){const id=identifier(local.slice(6));const result=await db.prepare("UPDATE farms SET published=0,revision=revision+1,updated_at=? WHERE id=?").bind(new Date().toISOString(),id).run();if(!result.meta.changes)return fail(404,"not_found","المزرعة غير موجودة.");return response({hidden:true,message:"تم إخفاء المزرعة عن الزبائن وحفظ سجلات حجوزاتها."});}
   if(local==="bookings"&&method==="GET"){const rows=await db.prepare("SELECT * FROM bookings ORDER BY created_at DESC LIMIT 500").all<BookingRow>();return response({bookings:rows.results.map(bookingJSON)});}
   if(/^bookings\/[a-zA-Z0-9-]+$/.test(local)&&method==="PATCH"){
    const id=identifier(local.slice(9)),value=await body(request),status=value.status;
    if(!["confirmed","rejected","cancelled"].includes(String(status)))return fail(400,"invalid_status","حالة غير صالحة.");
    const current=await db.prepare("SELECT * FROM bookings WHERE id=?").bind(id).first<BookingRow>();if(!current)return fail(404,"not_found","الطلب غير موجود.");
    if(current.status===status)return response({booking:bookingJSON(current)});
    if(status==="confirmed"){
     if(current.status!=="pending")return fail(409,"invalid_transition","يمكن تأكيد الطلب المعلق فقط.");
     try{const results=await db.batch([db.prepare("INSERT INTO reserved_dates(farm_id,date,period,booking_id) SELECT b.farm_id,b.date,p.period,b.id FROM bookings b CROSS JOIN (SELECT 'morning' AS period UNION ALL SELECT 'evening') p WHERE b.id=? AND b.status='pending' AND b.customer_name!='' AND (b.period=p.period OR b.period='full_day')").bind(id),db.prepare("UPDATE bookings SET status='confirmed' WHERE id=? AND status='pending' AND EXISTS(SELECT 1 FROM reserved_dates WHERE booking_id=?)").bind(id,id)]);if(!results[1].meta.changes)return fail(409,"booking_changed","الطلب تغير أو حُذفت بياناته. حدّث القائمة.");}catch(e){if(e instanceof Problem)throw e;return fail(409,"date_taken","هذه الفترة مؤكدة لحجز آخر. اختار الفترة الثانية أو يوماً آخر.");}
    }else{
     if(status==="rejected"&&current.status!=="pending")return fail(409,"invalid_transition","رفض الطلب متاح قبل التأكيد.");
     const changed=await db.batch([db.prepare("UPDATE bookings SET status=? WHERE id=? AND (status='pending' OR (?='cancelled' AND status='confirmed'))").bind(status,id,status),db.prepare("DELETE FROM reserved_dates WHERE booking_id=? AND EXISTS(SELECT 1 FROM bookings WHERE id=? AND status IN ('rejected','cancelled'))").bind(id,id)]);if(!changed[0].meta.changes)return fail(409,"booking_changed","الطلب تغير. حدّث القائمة.");
    }
    const updated=await db.prepare("SELECT * FROM bookings WHERE id=?").bind(id).first<BookingRow>();return response({booking:bookingJSON(updated!)});
   }
   if(local==="photos"&&method==="POST"){
    if(!env.STORAGE)return fail(503,"storage_not_ready","رفع الصور غير متاح حالياً.");await rate(db,"upload:"+session,40,3600);
    if(Number(request.headers.get("Content-Length")||0)>2200000)return fail(413,"image_too_large","اختار صورة أصغر من ٢ ميغابايت.");
    const form=await request.formData(),file=form.get("file");if(!(file instanceof File)||file.size<16||file.size>2097152)return fail(400,"invalid_image","صورة غير صالحة أو كبيرة.");
    const bytes=new Uint8Array(await file.arrayBuffer());let type="",ext="";
    if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255){type="image/jpeg";ext="jpg";}else if(bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71){type="image/png";ext="png";}else if(new TextDecoder().decode(bytes.slice(0,4))==="RIFF"&&new TextDecoder().decode(bytes.slice(8,12))==="WEBP"){type="image/webp";ext="webp";}
    if(!type||file.type!==type)return fail(400,"invalid_image","استخدم صورة JPG أو PNG أو WebP.");
    const key=crypto.randomUUID()+"."+ext;await env.STORAGE.put(key,bytes,{httpMetadata:{contentType:type}});return response({url:"/api/v2/photos/"+key},201);
   }
   return fail(404,"not_found","المسار غير موجود.");
  }
  if(/^photos\/[a-f0-9-]{36}\.(jpg|png|webp)$/.test(path)&&method==="GET"){
   const key=path.slice(7),publicRow=await db.prepare("SELECT id FROM farms WHERE published=1 AND EXISTS (SELECT 1 FROM json_each(farms.images) AS photo WHERE photo.value=?) LIMIT 1").bind("/api/v2/photos/"+key).first();if(!publicRow)await admin(request,env);
   const object=await env.STORAGE?.get(key);if(!object)return fail(404,"not_found","الصورة غير موجودة.");return new Response(object.body as unknown as BodyInit,{headers:{"Content-Type":object.httpMetadata?.contentType||"image/jpeg","Cache-Control":publicRow?"public,max-age=300":"no-store"}});
  }
  if(path==="unavailable"&&method==="GET"){const id=identifier(url.searchParams.get("farmId")||""),selected=url.searchParams.get("period");if(selected)period(selected);const rows=await db.prepare("SELECT date,period FROM reserved_dates WHERE farm_id=? AND date>=? ORDER BY date,period").bind(id,today()).all<{date:string;period:string}>();const slots=rows.results;const dates=selected?slots.filter(r=>r.period===selected).map(r=>r.date):Array.from(new Set(slots.map(r=>r.date))).filter(d=>slots.filter(r=>r.date===d).length===2);return response({dates,slots});}
  if(path==="bookings"&&method==="GET"){const hash=await device(request,db);const rows=await db.prepare("SELECT bookings.*, (SELECT stars FROM farm_reviews WHERE booking_id=bookings.id) AS review_stars FROM bookings WHERE device_hash=? ORDER BY created_at DESC LIMIT 100").bind(hash).all<BookingRow>();return response({bookings:rows.results.map(bookingJSON)});}
  if(path==="bookings"&&method==="POST"){
   const hash=await device(request,db),value=await body(request),farmId=identifier(text(value.farmId,80)),date=day(value.date),selectedPeriod=period(value.period),guests=number(value.guests,1,1000),name=text(value.name,100),telephone=phone(value.phone),notes=text(value.notes,1000,false),requestId=identifier(text(value.requestId,80));
   const payloadHash=await digest(JSON.stringify({farmId,date,period:selectedPeriod,guests,name,telephone,notes}));
   const previous=await db.prepare("SELECT * FROM bookings WHERE device_hash=? AND request_id=?").bind(hash,requestId).first<BookingRow>();
   if(previous){if(previous.payload_hash!==payloadHash)return fail(409,"request_conflict","هذا الطلب أُرسل بتفاصيل مختلفة. حدّث قائمة طلباتك.");return response({booking:bookingJSON(previous)});}
   await rate(db,"booking:"+hash,15,86400);await rate(db,"booking-ip:"+request.headers.get("CF-Connecting-IP"),50,3600);
   if(date<today()||date>new Date(Date.now()+366*86400000).toISOString().slice(0,10))return fail(400,"invalid_date","الحجز يبدأ من اليوم فصاعداً، وخلال السنة القادمة.");
   const farm=await db.prepare("SELECT * FROM farms WHERE id=? AND published=1").bind(farmId).first<FarmRow>();if(!farm)return fail(404,"not_found","المزرعة غير متاحة.");if(guests>farm.capacity)return fail(400,"over_capacity","عدد الزوار أكثر من سعة المزرعة.");
   const id=crypto.randomUUID();try{const result=await db.prepare("INSERT INTO bookings(id,device_hash,request_id,payload_hash,farm_id,farm_name,date,period,guests,customer_name,phone,notes,total,status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',? WHERE EXISTS(SELECT 1 FROM devices WHERE hash=? AND revoked=0) AND NOT EXISTS(SELECT 1 FROM reserved_dates WHERE farm_id=? AND date=? AND period=?)").bind(id,hash,requestId,payloadHash,farmId,farm.name,date,selectedPeriod,guests,name,telephone,notes,selectedPeriod==="evening"?(farm.evening_price??farm.price):farm.price,new Date().toISOString(),hash,farmId,date,selectedPeriod).run();if(!result.meta.changes)return fail(409,"date_taken","الفترة غير متاحة أو تغيرت بيانات الجهاز. حدّث المواعيد.");}catch(e){if(e instanceof Problem)throw e;const duplicate=await db.prepare("SELECT * FROM bookings WHERE device_hash=? AND request_id=?").bind(hash,requestId).first<BookingRow>();if(duplicate&&duplicate.payload_hash===payloadHash)return response({booking:bookingJSON(duplicate)});throw e;}
   const saved=await db.prepare("SELECT * FROM bookings WHERE id=?").bind(id).first<BookingRow>();return response({booking:bookingJSON(saved!)},201);
  }
  if(/^bookings\/[a-zA-Z0-9-]+\/cancel$/.test(path)&&method==="POST"){const hash=await device(request,db),id=identifier(path.split("/")[1]);await db.batch([db.prepare("UPDATE bookings SET status='cancelled' WHERE id=? AND device_hash=? AND status IN ('pending','confirmed')").bind(id,hash),db.prepare("DELETE FROM reserved_dates WHERE booking_id=? AND EXISTS(SELECT 1 FROM bookings WHERE id=? AND device_hash=? AND status='cancelled')").bind(id,id,hash)]);const row=await db.prepare("SELECT * FROM bookings WHERE id=? AND device_hash=?").bind(id,hash).first<BookingRow>();if(!row)return fail(404,"not_found","الطلب غير موجود على هذا الجهاز.");return response({booking:bookingJSON(row)});}
  if(path==="device"&&method==="DELETE"){const hash=await device(request,db,true);await db.batch([db.prepare("UPDATE devices SET revoked=1 WHERE hash=?").bind(hash),db.prepare("UPDATE bookings SET customer_name='',phone='',notes='',device_hash='erased:'||id WHERE device_hash=? AND status='confirmed'").bind(hash),db.prepare("DELETE FROM bookings WHERE device_hash=? AND status!='confirmed'").bind(hash)]);return response({deleted:true});}
  return fail(404,"not_found","المسار غير موجود.");
 }catch(e){if(e instanceof Problem)return response({error:{code:e.code,message:e.message},message:e.message},e.status);console.error("Mazraaty service failure",e);return response({error:{code:"service_error",message:"تعذر تنفيذ العملية. حاول مجدداً بعد قليل."}},503);}
}
